spring:
  datasource:
    name: wellup-user
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  port: 8081
  security:
    enabled: false

logging:
  level:
    com.dominichenko.test: ${LOGGING_LEVEL:DEBUG}

endpoints:
  cors:
    allow-credentials: true
    allowed-origins: ${ALLOWED_ORIGINS:*}
    allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - HEAD
    allowed-headers:
    - Accept
    - X-HTTP-Method-Override
    - Content-Type
    - Origin
    - Authorization
    max-age: 1209600

security:
  basic:
    enabled: false
